### ISSUE TITLE
Toast message is not visible in dark mode.

### ISSUE THREAD

**Issue by Quasilius-Starlord** [inovex/scrumlr.io#3433] opened 2023-10-07 19:40 UTC
## Problem description
Text in toast messages those pop-up when notes on a board are deleted aren't visible in dark mode.
This is an issue with the contrast ratio of toast message text and its background. Although aforementioned behavior isn't seen in light mode.
![bug_toast_message](https://github.com/inovex/scrumlr.io/assets/54246641/69ccc425-f008-4ada-acee-67fff3dba130)

### Browser

Chrome

### Steps to reproduce the behavior

- Create a new board.
- Create a note.
- Delete the note and notice the toast message that appear in lower right part of your screen doesn't have any readable text.

### Screenshots

![bug_toast_message](https://github.com/inovex/scrumlr.io/assets/54246641/69ccc425-f008-4ada-acee-67fff3dba130)

**Comment by blxckOxymoron** [comment] 2023-10-09 08:13
I've noticed this in firefox as well, the border radius is also wrong

this is caused by the lack of support for the css `:has()` selector. 
similar to #3048 we need to see how much of a workaround would be needed

looking at https://caniuse.com/css-has, the feature is suported in 87% of browsers with firefox being the only browser that doesen't support it in their latest version

**Comment by blxckOxymoron** [comment] 2023-10-09 08:45
found it:
https://github.com/inovex/scrumlr.io/blob/7dc3b5f7a76cb773d89dceaf53a9ceb53f2c81e2/src/components/CustomToast/CustomToast.scss#L307-L310
but I think the has maybe isn't even necessary here

**Comment by brandstetterm** [comment] 2024-01-02 10:08
Thank you for your bug report @Quasilius-Starlord. Currently I cannot reproduce the bug. It may have already been fixed by one of our changes. The toast that is displayed for me in the Chrome browser when I delete a note is as follows: 
![scrumlr io_board_c797dd59-e1e4-45bd-9929-f755e0cd41af](https://github.com/inovex/scrumlr.io/assets/36969812/9a4e3987-f1bd-4721-9e46-8c7ad2b97f42)

Can you check if you are still experiencing the bug?

**Closed** 2024-03-21 08:56 UTC
Labels: Unverified Bug
