### ISSUE TITLE
Better HTTP status codes for board join requests

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#3920] opened 2024-02-29 13:27 UTC
Currently, the backend returns the 403 code for multiple occasions:
- User tries to connect to a protected board the first time (without a password)
- User tries to connect to a protected board with the wrong password
- User is banned from a session

We should have different status codes for these cases, so that we can handle them better in the frontend. Right now, to check if a user is banned, we need to match the whole error string, which is not ideal imo.

**Comment by Schwehn42** [comment] 2024-03-04 08:35
I think semantically, [401](https://http.cat/401) is the most fitting status code for the first and second use case.   
Maybe one could use the [realm attribute defined in the WWW specs](https://datatracker.ietf.org/doc/html/rfc1945#section-11) to further clarify which is which.

As for banning users, [403](https://http.cat/403) should be the correct one, because the user doesn't have the wrong credentials, but is explicitly disallowed in that session :)

**Comment by brandstetterm** [comment] 2024-03-04 18:53
> I think semantically, [401](https://http.cat/401) is the most fitting status code for the first and second use case. Maybe one could use the [realm attribute defined in the WWW specs](https://datatracker.ietf.org/doc/html/rfc1945#section-11) to further distinct the two.
> 
> As for banning users, [403](https://http.cat/403) should be the correct one, because the user doesn't have the wrong credentials, but is explicitly disallowed in that session :)

Although the 401 status code says unauthorized, semantically this response means unauthenticated. Therefore, it is not semantically correct to use it. @Schwehn42

**Comment by brandstetterm** [comment] 2024-03-06 13:26
Closed because it's a duplicate of [#3940](https://github.com/inovex/scrumlr.io/issues/3940)

**Closed by brandstetterm** 2024-03-06 13:26 UTC
Labels: Good First Issue
