### ISSUE TITLE
Refine avatar indicators

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#1819] opened 2022-06-15 06:30 UTC
AC:
- [ ] The raised hand and ready indicators next to the avatar symbol should be refined, e.g. raised hand + ready = border color and raised hand icon color are different. Idea: circle behind icons, change icon location, remove ready-state border...
- [ ] The green color of the ready state should be changed to dark/light in alignment with the menu bar items.

![Image](https://user-images.githubusercontent.com/32651718/182360678-5b73533e-5474-44dd-9dfa-e21bb00cee45.png)

![Image](https://user-images.githubusercontent.com/32651718/182360849-f92651c0-2190-483e-b6ea-c999f2462752.png)

**Comment by Kraft-16** [comment] 2022-07-05 16:20
Light Mode:
https://xd.adobe.com/view/1b6fac62-e701-4205-8841-b1b74586c0e0-4e3c/
https://xd.adobe.com/view/927cca2b-aca6-422f-b545-3c38fa183875-c72f/
https://xd.adobe.com/view/96d8715f-bdb4-4749-8c8a-ee86a4f98e6f-c38b/
https://xd.adobe.com/view/d9170888-3a92-4f2f-8e1c-4b3c44b293bc-8c44/
Dark Mode:
https://xd.adobe.com/view/5ce9b1b9-4d2a-4b86-950d-d73097ef8713-09ba/
https://xd.adobe.com/view/ec15b2d6-5e08-4c13-a577-2def684afbcc-b946/
https://xd.adobe.com/view/7101df88-df90-453b-b307-29d4f4ec783d-2452/
https://xd.adobe.com/view/50876af9-710c-4943-9109-4c250103a185-05d4/

**Comment by bitionaire** [comment] 2022-08-30 06:03
Duplicate of [#2084](https://github.com/inovex/scrumlr.io/issues/2084)

**Closed by bitionaire** 2022-08-30 06:03 UTC
